POST https://dev-u88hggl2gixpsbz4.us.auth0.com/oauth/token HTTP/1.1
content-type: application/json

{
  "client_id":"PdI1TzprNYmhOvhAp3Y4VzuHjlqmXk19",
  "client_secret":"h1BvoMzjIawVeBAXbaHQ9KRzpcdqW1N95U0MoWS1f7W53j8sfeNPVFDjof5fxos_",
  "audience":"https://interview-tracker/auth",
  "grant_type":"client_credentials"
}

POST http://localhost:3000/graphql HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjlTaEdFWHVVZWt1eGwwWEd1VWpxNyJ9.eyJpc3MiOiJodHRwczovL2Rldi11ODhoZ2dsMmdpeHBzYno0LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJQZEkxVHpwck5ZbWhPdmhBcDNZNFZ6dUhqbHFtWGsxOUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9pbnRlcnZpZXctdHJhY2tlci9hdXRoIiwiaWF0IjoxNzU2NTQ1NTEzLCJleHAiOjE3NTY2MzE5MTMsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6IlBkSTFUenByTlltaE92aEFwM1k0Vnp1SGpscW1YazE5In0.tZ3aWsoUW0KDFXujOHI_wkJmAVRPjORs4kHKyIfhqv7_tAktDcvuNXq2XmMoyBaiok_0bYuRbO0PuEcwZ9GJim6eFh324Hn1ICF_77EoiTtV2COkxQVAkv4lyLcVmkimMbWIFAsrtg8I0LhtKoTT3blJKTHuf0q40IFmKj9IJ6gr_jbqcvUxVY2puhwXi5g4B0dcH5TmKw52XY_8Tu8fSwj0ZLEOee5AlNXqpfgwjyRlIGhGDUjwwHiveoPRazYEGI9vYuojEJbecTnBrnqnotjfgK3D9kgKwZtjHtqG0JLDqvkxkL2mL_tpm4LCbd33UrudTzTPVNOxlbSeh1NvVQ

{
  "query": "{ interviews { company } }"
}